version: '3'
services:
  webapp:
    container_name: webapp
    build: .
    command: /bin/sh -c "bundle exec puma -t 6:24 -w 2"
    volumes:
      - .:/app:rw
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    env_file: .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:11.5-alpine
    ports:
      - 5439:5432
    volumes:
      - data-performance:/var/lib/postgresql/data
    env_file: .env
volumes:
  data-performance:
    driver: local
